### ISSUE TITLE
Refactor Mocked data to follow the Frictionless specs

### ISSUE THREAD

**Issue by lauragift21** [datopian/portal#11]
Mocked data should follow the Frictionless specs e.g. for dataset page Data Package, for resource use Data Resource spec

## Acceptance
* [x] Mocked data follows the Frictionless Data specs approach

## Tasks
* [x] Refactor current mocked resource page table to follow the data resource spec

**Comment by anuveyatsu** [comment]
FIXED, see https://github.com/datopian/portal/blob/master/mocks/index.js
